SHELL=bash
TARGET=CN1.pdf
LL=latexmk -pdf
CLEAN=latexmk -C

all: revision.tex $(TARGET) refresh

pdf: revision.tex $(TARGET) refresh

.PHONY : clean revision.tex contributors.tex $(TARGET) refresh mupdf

revision.tex:
	echo "% Autogenerated, do not edit" > revision.tex
	echo "\\newcommand{\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> revision.tex
	echo "\\newcommand{\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex

contributors.tex:
	echo "% Autogenerated, do not edit" > contributors.tex
	echo "\\newcommand{\\contributors}{`awk '{split($$0, a, \"(\"); gsub(/[ \t]+$$/, \"\", a[1]); printf(\"%s, \", a[1])}' CONTRIBUTORS.txt | sed 's/, $$//'`}" >> contributors.tex

$(TARGET): $(TARGET:%.pdf=%.tex) $(SRC)
	$(LL) $<

clean:
	$(CLEAN)
	rm -f revision.tex

refresh:
	-killall -HUP mupdf ||  echo "Mupdf not started, no refreshing."

mupdf:
	mupdf $(TARGET) &

# vim: set tabstop=4 shiftwidth=4 noexpandtab:
